options:
  openstack-origin:
    default: distro
    type: string
    description: |
      Repository from which to install.  May be one of the following:
      distro (default), ppa:somecustom/ppa, a deb url sources entry,
      or a supported Cloud Archive release pocket.
      Supported Cloud Archive sources include:
      cloud:<series>-<openstack-release>
      cloud:<series>-<openstack-release>/updates
      cloud:<series>-<openstack-release>/staging
      cloud:<series>-<openstack-release>/proposed
      For series=Xenial we support cloud archives for openstack-release:
         * Mitaka
      NOTE: updating this setting to a source that is known to provide
      a later version of OpenStack will trigger a software upgrade.
  rabbit-user:
    default: barbican
    type: string
    description: Username used to access rabbitmq queue
  rabbit-vhost:
    default: openstack
    type: string
    description: Rabbitmq vhost
  database-user:
    default: barbican
    type: string
    description: Username for Neutron database access (if enabled)
  database:
    default: barbican
    type: string
    description: Database name for Neutron (if enabled)
  debug:
    default: False
    type: boolean
    description: Enable debug logging
  verbose:
    default: False
    type: boolean
    description: Enable verbose logging
  region:
    default: RegionOne
    type: string
    description: OpenStack Region
  keystone-api-version:
    default: "3"
    type: string
    description: none,  2 or 3